### ISSUE TITLE
Running `convert-h5-to-ggml.py` on distil-whisper gives a HeaderTooLarge error

### ISSUE THREAD

**Issue by PoignardAzur** [ggml-org/whisper.cpp#1711]
I followed the steps outlined in [models/README.md](https://github.com/ggerganov/whisper.cpp/blob/master/models/README.md):

```sh
git clone https://github.com/ggerganov/whisper.cpp
git clone https://huggingface.co/distil-whisper/distil-medium.en
git clone https://huggingface.co/distil-whisper/distil-large-v2

# convert to ggml
python3 whisper.cpp/models/convert-h5-to-ggml.py distil-medium.en/ whisper.cpp/ some-output-folder/
```

Doing so gives me the following stack trace:

```
Traceback (most recent call last):
  File "/home/olivier-faure/Documents/whisper.cpp/models/convert-h5-to-ggml.py", line 87, in <module>
    model = WhisperForConditionalGeneration.from_pretrained(dir_model)
  File "/home/olivier-faure/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3372, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

I've confirmed with print-debugging that the file being opened is `distil-medium.en/model.safetensors`. I have the same problem with distil-large-v2.

**Comment by bobqianic** [comment]
>python3 whisper.cpp/models/convert-h5-to-ggml.py distil-medium.en/ whisper.cpp/ some-output-folder/

Replace `whisper.cpp/` with the path to the OpenAI Whisper repository.

See https://github.com/ggerganov/whisper.cpp/discussions/1414#discussioncomment-7461216

**Comment by PoignardAzur** [comment]
Well oops.

I still get the same error though:

```sh
> python3 models/convert-h5-to-ggml.py distil-medium.en/ whisper/ ~/Documents/models/
file being open:  /home/olivier-faure/Documents/distil-medium.en/model.safetensors
Traceback (most recent call last):
  File "/home/olivier-faure/Documents/whisper.cpp/models/convert-h5-to-ggml.py", line 87, in <module>
    model = WhisperForConditionalGeneration.from_pretrained(dir_model)
  File "/home/olivier-faure/Documents/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3372, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by samolego** [comment]
Hi, I've finetuned whisper myself for [Slovenian laguage](https://huggingface.co/samolego/whisper-small-sl-mozilla). I'm running command:
```bash
python ./whisper.cpp/models/convert-h5-to-ggml.py ./whisper-small-sl-mozilla ./whisper .
```

But also get the `HeaderTooLarge` error:
```
Traceback (most recent call last):
  File "/home/samoh/Documents/school/3.letnik/diploma/./whisper.cpp/models/convert-h5-to-ggml.py", line 87, in <module>
    model = WhisperForConditionalGeneration.from_pretrained(dir_model)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/samoh/Documents/school/3.letnik/diploma/test_whisper/.venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3284, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

**Comment by dturaev** [comment]
One possible problem is explained in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8123: After cloning the repository, you need git lfs to download the actual model files, something like:

```sh
conda install -c conda-forge git-lfs
git clone <repo>
cd <repo>
git lfs install
git lfs pull
```
