### ISSUE TITLE
Cannot generate CoreML model

### ISSUE THREAD

**Issue by aviaryan** [ggml-org/whisper.cpp#2423]
I am following the instructions given in the README. However, I am not able to generate a CoreML model.

I did the following steps -

```sh
conda create -n py310-whisper python=3.10 -y
conda activate py310-whisper
pip install ane_transformers
pip install openai-whisper
pip install coremltools
./models/generate-coreml-model.sh base.en
```

And this is the error I get -

```sh
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/aviaryan/dev/__others/whisper.cpp/models/convert-whisper-to-coreml.py", line 2, in <module>
    import torch
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/torch/__init__.py", line 870, in <module>
    from . import _masked
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/torch/_masked/__init__.py", line 420, in <module>
    def sum(input: Tensor,
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/torch/_masked/__init__.py", line 223, in _apply_docstring_templates
    example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/torch/_masked/__init__.py:223: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at  /Users/distiller/project/pytorch/torch/csrc/utils/tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
Minimum required torch version for importing coremltools.optimize.torch is 2.1.0. Got torch version 1.11.0.
Traceback (most recent call last):
  File "/Users/aviaryan/dev/__others/whisper.cpp/models/convert-whisper-to-coreml.py", line 4, in <module>
    import coremltools as ct
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/__init__.py", line 121, in <module>
    from . import converters, models, optimize, proto
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/__init__.py", line 7, in <module>
    from . import libsvm, sklearn, xgboost
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/libsvm/__init__.py", line 8, in <module>
    from . import _libsvm_converter, _libsvm_util
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/libsvm/_libsvm_converter.py", line 7, in <module>
    from coremltools.models import _METADATA_SOURCE, _METADATA_VERSION
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/models/__init__.py", line 12, in <module>
    from . import pipeline
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/models/pipeline.py", line 12, in <module>
    from . import model as _model
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/models/model.py", line 26, in <module>
    from coremltools.converters.mil.mil.program import Program as _Program
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/mil/__init__.py", line 15, in <module>
    from .frontend.tensorflow.tf_op_registry import register_tf_op
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/mil/frontend/__init__.py", line 6, in <module>
    from . import tensorflow, tensorflow2, torch
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/__init__.py", line 11, in <module>
    from . import ops, quantization_ops
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/ops.py", line 37, in <module>
    from .internal_graph import InternalTorchIRGraph, InternalTorchIRNode
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/internal_graph.py", line 15, in <module>
    from .exir_utils import extract_io_from_exir_program
  File "/Users/aviaryan/miniconda3/envs/py310-whisper/lib/python3.10/site-packages/coremltools/converters/mil/frontend/torch/exir_utils.py", line 100, in <module>
    ) -> Dict[str, torch.fx.Node]:
AttributeError: module 'torch' has no attribute 'fx'
coremlc: error: Model does not exist at models/coreml-encoder-base.en.mlpackage -- file:///Users/aviaryan/dev/__others/whisper.cpp/
mv: rename models/coreml-encoder-base.en.mlmodelc to models/ggml-base.en-encoder.mlmodelc: No such file or directory
```

----

Since Python dependency versions vary depending on when you run `pip install`, maybe someone can provide a lock file like a [Pipfile.lock file](https://github.com/pypa/pipenv) that will always work.

**Comment by hagmonk** [comment]
To get this to work I had to do:

```
pip install "numpy<2"
pip install torch==2.1.0
```

**Comment by OutisLi** [comment]
> To get this to work I had to do:
> 
> ```
> pip install "numpy<2"
> pip install torch==2.1.0
> ```

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ane-transformers 0.1.3 requires torch<=1.11.0,>=1.10.0, but you have torch 2.1.0 which is incompatible.
how to solve this

**Comment by reeteshranjan** [comment]
> ```shell
> pip install coremltools
> ```

For me, this sequence worked
```zsh
pip install "numpy<2"
pip install ane_transformers
```
Above installs torch-1.11.0
```zsh
pip install torch==2.1.0
```
The above produces the pip warning. But I ignored it.

```zsh
pip install openai-whisper
pip install coremltools
```

**Comment by reeteshranjan** [comment]
```text
ane_transformers==0.1.3
attrs==24.2.0
cattrs==24.1.2
certifi==2024.12.14
charset-normalizer==3.4.0
coremltools==8.1
exceptiongroup==1.2.2
filelock==3.16.1
fsspec==2024.10.0
huggingface-hub==0.26.5
idna==3.10
Jinja2==3.1.4
llvmlite==0.43.0
MarkupSafe==3.0.2
more-itertools==10.5.0
mpmath==1.3.0
networkx==3.4.2
numba==0.60.0
numpy==1.26.4
openai-whisper==20240930
packaging==24.2
protobuf==3.20.1
pyaml==24.12.1
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
safetensors==0.4.5
sympy==1.13.3
tiktoken==0.8.0
tokenizers==0.21.0
torch==2.1.0
tqdm==4.67.1
transformers==4.47.0
typing_extensions==4.12.2
urllib3==2.2.3
```

This works for me. Can get the conversion to coreml format done. Hope this is helpful.

**Comment by akhil-m** [comment]
^ That list of requirements does not work

Seems ane_transformers requires torch 1.10 to 1.11 and coremltools requires torch 2.1.0?

**Comment by reeteshranjan** [comment]
Remove torch from the requirements list. Install everything else using the changed requirements list. Then, install torch==2.1.0. It works for me with this.On 23 Dec 2024, at 1:16 AM, akhil-m ***@***.***> wrote:﻿
^ That list of requirements does not work
Seems ane_transformers requires torch 1.10 to 1.11 and coremltools requires torch 2.1.0?

**Comment by tinoargentino** [comment]
These ones worked for me after failing with the above ones
```
python -m venv .venv
source .venv/bin/activate
pip install numpy==1.24.3  # A stable 1.x version
pip install torch torchvision torchaudio
pip install -r requirements.txt  # If there's a requirements.txt file
```

**Comment by oxcabe** [comment]
For anyone else using `uv`, it won't let you install `torch==2.1.0` unless you explicitly override the dependency in `pyproject.toml`.

This worked for me:

`pyproject.toml`:
```toml
[project]
name = "whisper-cpp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ane-transformers>=0.1.3",
    "coremltools",
    "numpy<2",
    "openai-whisper",
    "torch==2.1.0",
]

[tool.uv]
override-dependencies = ["torch==2.1.0"]
```
