### ISSUE TITLE
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] when attempting to generate CoreML model of large-v3-turbo

### ISSUE THREAD

**Issue by 7k50** [ggml-org/whisper.cpp#2461]
I was attempting to run `./models/generate-coreml-model.sh large-v3-turbo` as seen below – unsure what the problem is here.

```
./models/generate-coreml-model.sh large-v3-turbo
Py copy310-cwhisper
 75%|███████████████████████████▌         | 1.12G/1.51G [01:37<00:33, 12.4MiB/s]
Traceback (most recent call last):
  File "/Users/username/GitHub/whisper.cpp/models/convert-whisper-to-coreml.py", line 295, in <module>
    whisper = load_model(args.model).cpu()
  File "/Users/username/Coding/Languages/Python/Virtual/copy310-cwhisper/lib/python3.10/site-packages/whisper/__init__.py", line 137, in load_model
    checkpoint_file = _download(_MODELS[name], download_root, in_memory)
  File "/Users/username/Coding/Languages/Python/Virtual/copy310-cwhisper/lib/python3.10/site-packages/whisper/__init__.py", line 82, in _download
    buffer = source.read(8192)
  File "/Users/username/Coding/Languages/Python/Virtual/copy310-cwhisper/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/Users/username/Coding/Languages/Python/Virtual/copy310-cwhisper/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/username/Coding/Languages/Python/Virtual/copy310-cwhisper/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/username/Coding/Languages/Python/Virtual/copy310-cwhisper/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)
coremlc: error: Model does not exist at models/coreml-encoder-large-v3-turbo.mlpackage -- file:///Users/username/GitHub/whisper.cpp/
mv: rename models/coreml-encoder-large-v3-turbo.mlmodelc to models/ggml-large-v3-turbo-encoder.mlmodelc: No such file or directory
```

Prior to this, I downloaded large-v3-turbo model:
`bash ./models/download-ggml-model.sh large-v3-turbo`

…after doing the ordinary update steps of whisper.cpp.

Any ideas? This is on v1.7.0.

Can I reset the situation somehow (e.g. by deleting a model related file) – or do I need to delete everything and start from a new virtual environment?

**Comment by lithium0003** [comment]
weight path seems to changed

try
https://huggingface.co/ggerganov/whisper.cpp/tree/main

**Comment by 7k50** [comment]
> weight path seems to changed
> 
> try https://huggingface.co/ggerganov/whisper.cpp/tree/main

Thanks, I was able to simply download `ggml-large-v3-turbo-encoder.mlmodelc.zip`, extract `ggml-large-v3-turbo-encoder.mlmodelc`, and place it in `whisper.cpp/models`.
