### ISSUE TITLE
main.cpp tool core dumps after installation.

### ISSUE THREAD

**Issue by bigopensky** [ggml-org/whisper.cpp#789]
I try to install ~whisper.cpp~ to run ~whisper.el~. The installation runs but the ~main~ tool core dumps.

# Install and call ...

```bash
 cmake .
 make
 ./bin/main -f samples/jfk.wav 
whisper_init_from_file_no_state: loading model from 'models/ggml-base.en.bin'
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 512
whisper_model_load: n_audio_head  = 8
whisper_model_load: n_audio_layer = 6
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 512
whisper_model_load: n_text_head   = 8
whisper_model_load: n_text_layer  = 6
whisper_model_load: n_mels        = 80
whisper_model_load: f16           = 1
whisper_model_load: type          = 2
whisper_model_load: mem required  =  218.00 MB (+    6.00 MB per decoder)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: model ctx     =  140.60 MB
Illegal instruction (core dumped)

```

# OS

```bash
$uname -a
OS: Linux zulu 5.4.0-144-generic #161~18.04.1-Ubuntu SMP Fri Feb 10 15:55:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
# CPU 

```bash
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz
stepping	: 4
microcode	: 0x42e
cpu MHz		: 1200.080
cache size	: 30720 KB
physical id	: 0
siblings	: 24
core id		: 0
cpu cores	: 12
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 5400.09
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
...
```

**Comment by tbswork1** [comment]
I have the same problem. Core dump trace:

```
Core was generated by `./bin/main -f samples/jfk.wav'.
Program terminated with signal SIGILL, Illegal instruction.
Privileged opcode.
#0  0x00000008002a55f6 in ggml_type_sizef () from git/whisper.cpp/libwhisper.so
(gdb) bt
#0  0x00000008002a55f6 in ggml_type_sizef () from git/whisper.cpp/libwhisper.so
#1  0x00000008002d3a7e in whisper_model_load(whisper_model_loader*, whisper_context&) ()
   from git/whisper.cpp/libwhisper.so
#2  0x00000008002d2b26 in whisper_init_no_state () from git/whisper.cpp/libwhisper.so
#3  0x00000008002d298c in whisper_init_from_file_no_state () from git/whisper.cpp/libwhisper.so
#4  0x00000008002da8dc in whisper_init_from_file () from git/whisper.cpp/libwhisper.so
#5  0x000000000021c0bc in main ()
```

**Comment by Nik-Kras** [comment]
I had the same problem. Whenever I attempted loading a model - I got "Illegal instruction (core dumped)".
Here I found the the issue could be in the CPU and it worked for me.

I got this error on a server with Xeon E5-2687W CPU (manufactured back in 2012)
When I changed it to AMD Ryzen Threadripper PRO 5955WX (2022) - all worked fine.

If that doesn't help you, I also found that it could be a bug with numpy, try downgrading in to 1.19.4
