### ISSUE TITLE
Python support for >3.11

### ISSUE THREAD

**Issue by darklight147** [ggml-org/whisper.cpp#793]
Am on M1 pro, and following your guide at https://github.com/ggerganov/whisper.cpp#core-ml-support

the step which installs the openai-whisper

```sh
pip3 install openai-whisper --upgrade
```

throws the following error

```
Collecting numba
  Using cached numba-0.56.4.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/9y/7tfgw2c95ydcttg4h8yy8lgw0000gn/T/pip-install-agymynwp/numba_7bf65aad8cf448d6bd69925326cb0980/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/private/var/folders/9y/7tfgw2c95ydcttg4h8yy8lgw0000gn/T/pip-install-agymynwp/numba_7bf65aad8cf448d6bd69925326cb0980/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.3; only versions >=3.7,<3.11 are supported.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

the erros says that the package might only work with less than 3.11, so please mention it on your README or correct me if am doing something wrong, am on python version: `3.11.3`

**Comment by jeffla** [comment]
Yes. It's failing at numba - kind of a thing. I'm having the same problem - new to Python development. 

You'll have to ask one of your Python buddies to build it for you (assuming they already have the necessary dependencies installed). 

Don't have Python buddies? Now is the time to make new friends. It's the price of living on the bleeding edge.

Feel free to down-vote as I realize it isn't helpful. 😂

**Comment by jkrimmer** [comment]
Although numba 0.56.4 (not compatible with python 3.11 yet) is the default choice, numba 0.57rc1 is now available via pip. Hence, use `pip install numba==0.57rc1` to install numba on python 3.11.

**Comment by SlapakAlon** [comment]
Thanks BUDDY
